language: php
 
# Install Haxe before running the test.
before_script:
  - sudo apt-get install python-software-properties -y # for the next command
  - sudo add-apt-repository ppa:eyecreate/haxe -y      # add the ubuntu ppa that contains haxe
  - sudo apt-get update                                # pull info from ppa
  - sudo apt-get install haxe -y                       # install haxe (and neko)
  - sudo apt-get install gcc-multilib g++-multilib -y  # VM is 64bit but hxcpp builds 32bit
  - mkdir ~/haxelib                                    # create a folder for installing haxelib
  - haxelib setup ~/haxelib
  - haxelib install hxcpp                              # install hxcpp to test C++ target
  - haxelib install flixel                             # install HaxeFlixel with dependencies
  - haxelib git flixel-dev https://github.com/HaxeFlixel/flixel.git dev
  - haxelib install actuate
  - haxelib install nape
  - haxelib install openfl
  - haxelib install openfl-native
  - haxelib install openfl-compatibility
  - haxelib install openfl-tools
  - haxelib install svg
  - mkdir bin                                          # create an output folder if needed
 
# Run the test!
script:
  - ./build.sh